In [17]:
##This is a Basic MATH Nerual Optimization Model based on Assumption

In [18]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.preprocessing import LabelEncoder
data = pd.read_csv('train.csv')

In [19]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [20]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [21]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [22]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)

Iteration:  0
[2 7 6 ... 6 7 0] [7 2 1 ... 4 4 3]
0.09617073170731708
Iteration:  10
[2 6 6 ... 6 6 0] [7 2 1 ... 4 4 3]
0.11821951219512195
Iteration:  20
[2 6 6 ... 6 6 0] [7 2 1 ... 4 4 3]
0.13
Iteration:  30
[0 6 6 ... 6 6 0] [7 2 1 ... 4 4 3]
0.15951219512195122
Iteration:  40
[0 6 6 ... 6 6 0] [7 2 1 ... 4 4 3]
0.1865609756097561
Iteration:  50
[0 6 6 ... 6 6 0] [7 2 1 ... 4 4 3]
0.22319512195121952
Iteration:  60
[0 6 6 ... 6 6 0] [7 2 1 ... 4 4 3]
0.2782926829268293
Iteration:  70
[0 6 6 ... 4 6 0] [7 2 1 ... 4 4 3]
0.338
Iteration:  80
[0 7 6 ... 4 6 0] [7 2 1 ... 4 4 3]
0.3840731707317073
Iteration:  90
[2 7 6 ... 4 6 0] [7 2 1 ... 4 4 3]
0.4390731707317073
Iteration:  100
[2 7 8 ... 4 5 0] [7 2 1 ... 4 4 3]
0.4914878048780488
Iteration:  110
[2 7 8 ... 4 5 0] [7 2 1 ... 4 4 3]
0.5288048780487805
Iteration:  120
[2 7 8 ... 4 9 0] [7 2 1 ... 4 4 3]
0.5574146341463415
Iteration:  130
[7 7 8 ... 4 9 0] [7 2 1 ... 4 4 3]
0.5802682926829268
Iteration:  140
[7 7 8 ... 9 9 0] [7 2 1

In [23]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_prop(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = X_train[:, index, None]
    prediction = make_predictions(X_train[:, index, None], W1, b1, W2, b2)
    label = Y_train[index]
    print("Prediction: ", prediction)
    print("Label: ", label)
    


In [24]:
test_prediction(0, W1, b1, W2, b2)
test_prediction(1, W1, b1, W2, b2)
test_prediction(2, W1, b1, W2, b2)
test_prediction(3, W1, b1, W2, b2)

Prediction:  [7]
Label:  7
Prediction:  [7]
Label:  2
Prediction:  [1]
Label:  1
Prediction:  [8]
Label:  8


In [25]:
dev_predictions = make_predictions(X_dev, W1, b1, W2, b2)
get_accuracy(dev_predictions, Y_dev)

[7 0 1 3 9 7 8 1 1 0 8 9 7 8 7 5 0 1 9 2 5 5 0 6 0 5 8 8 5 1 7 6 2 5 1 9 4
 4 6 5 2 7 0 0 9 5 1 9 9 6 7 5 9 1 1 8 2 0 0 9 8 0 8 1 8 9 5 9 2 3 6 7 2 6
 7 8 2 2 0 4 6 2 8 5 9 0 7 7 8 1 4 7 0 7 6 3 7 1 4 0 0 3 9 5 8 5 2 6 7 7 3
 9 3 2 3 1 8 7 2 7 3 3 8 7 4 2 4 7 4 8 6 5 1 2 3 8 7 3 9 4 4 3 0 6 0 7 8 0
 8 4 8 7 8 6 2 7 1 6 4 3 2 2 3 2 9 7 7 3 8 1 3 9 7 8 7 0 7 9 1 1 9 7 6 9 1
 1 2 5 1 7 0 2 8 0 9 9 9 0 5 7 8 8 3 7 2 7 2 3 7 5 1 9 5 7 2 4 9 4 1 9 1 4
 0 3 3 2 2 4 3 1 2 6 8 5 0 5 2 9 5 3 4 2 8 2 0 3 0 0 9 4 2 1 5 3 7 3 9 7 4
 4 5 7 1 2 1 2 3 8 8 7 4 6 5 4 3 9 3 7 1 8 3 5 6 1 0 0 5 5 7 9 9 9 1 1 2 2
 9 8 8 8 6 7 0 6 7 4 8 9 2 6 7 5 4 3 1 9 3 9 1 2 8 9 3 1 7 9 0 9 2 1 5 4 4
 8 3 3 7 3 4 4 7 4 3 1 8 4 7 3 1 0 3 3 6 5 9 7 2 0 4 5 0 3 9 1 3 1 1 6 3 3
 9 1 9 2 6 5 4 4 7 2 7 4 6 8 7 1 1 6 0 8 4 6 4 7 7 8 7 9 0 5 1 3 8 1 3 6 5
 8 8 6 1 0 2 8 8 4 1 1 1 4 6 1 9 6 5 6 2 4 7 3 0 0 3 6 8 6 3 2 4 2 2 7 3 1
 3 7 9 1 0 8 1 4 0 3 5 5 7 0 6 5 9 3 4 2 4 0 6 7 7 6 8 9 2 9 6 6 7 7 9 1 3
 6 9 5 2 4 3 2 6 7 3 1 1 

0.838